import hashlib, pickle, marshal, yaml, subprocess, requests, os, ssl, tempfile
from flask import render_template_string
from django.utils.safestring import mark_safe
from lxml import etree
def a(s): return eval(s)
def b(s): return exec(s)
def ssti(t): return render_template_string(t)
def c1(cmd): return os.system(cmd)
def c2(cmd): return os.popen(cmd)
def c3(cmd): return subprocess.call(cmd, shell=True)
def d1(blob): return pickle.loads(blob)
def d2(blob): return yaml.load(blob)
def d3(blob): return marshal.loads(blob)
def q1(cur, name): return cur.execute("SELECT * FROM u WHERE n='%s'" % name)
def q2(cur, name): return cur.execute("SELECT * FROM u WHERE n=" + name)
def q3(cur, name): return cur.execute("SELECT * FROM u WHERE n={}".format(name))
def x(data): return etree.XMLParser(resolve_entities=True)
def h1(x): return hashlib.md5(x).hexdigest()
def h2(x): return hashlib.sha1(x).hexdigest()
def t1(u): return requests.get(u, verify=False)
def t2(): return ssl._create_unverified_context()
def xss(v): return mark_safe(v)
def tmp(): return tempfile.mktemp()
def ssrf(base, p): return requests.get(base + p)
def ssrf2(base, p): return urllib.request.urlopen(base + p)
def pt(d, n): return open(d + n)
